### ISSUE TITLE
Update docs for new stuff

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/rust_radix_trie#24]

**Comment by roblabla** [comment]
Thing is, there are a few functions which I think should not be exported that are because of the modularization. 

For instance, the `SubTrie::new()` constructor, or the various iter constructors.

It'd be nice if those symbols weren't exported, since they're (AFAIK) implementation details the usesr isn't meant to use.

**Comment by michaelsproul** [comment]
My thoughts exactly. I've been meaning to ask on #rust if there's a better way to structure the modules. One option might be to an `internals` module, which contains all the private functions, and then all the public functions in submodules like `internals::subtrie`. Then we just re-export the public types...

**Comment by vks** [comment]
What needs to be done for this? Every function is documented as far as I can see. I guess adding examples would help a lot.
